In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [42]:
df=pd.read_csv("Desktop/data/titanic.csv")
df.head()

PassengerId                                               Name  Pclass  \
0            1                            Braund, Mr. Owen Harris       3   
1            2  Cumings, Mrs. John Bradley (Florence Briggs Th...       1   
2            3                             Heikkinen, Miss. Laina       3   
3            4       Futrelle, Mrs. Jacques Heath (Lily May Peel)       1   
4            5                           Allen, Mr. William Henry       3   

      Sex   Age  SibSp  Parch            Ticket     Fare Cabin Embarked  \
0    male  22.0      1      0         A/5 21171   7.2500   NaN        S   
1  female  38.0      1      0          PC 17599  71.2833   C85        C   
2  female  26.0      0      0  STON/O2. 3101282   7.9250   NaN        S   
3  female  35.0      1      0            113803  53.1000  C123        S   
4    male  35.0      0      0            373450   8.0500   NaN        S   

   Survived  
0         0  
1         1  
2         1  
3         1  
4         0

In [43]:
df.drop(['PassengerId','Name','SibSp','Parch','Ticket','Cabin','Embarked'],axis='columns',inplace=True)
df.head()

Pclass     Sex   Age     Fare  Survived
0       3    male  22.0   7.2500         0
1       1  female  38.0  71.2833         1
2       3  female  26.0   7.9250         1
3       1  female  35.0  53.1000         1
4       3    male  35.0   8.0500         0

In [44]:
target=df.Survived
inputs=df.drop('Survived',axis='columns',inplace=True)
target.head()

0    0
1    1
2    1
3    1
4    0
Name: Survived, dtype: int64

In [45]:
df

Pclass     Sex   Age     Fare
0         3    male  22.0   7.2500
1         1  female  38.0  71.2833
2         3  female  26.0   7.9250
3         1  female  35.0  53.1000
4         3    male  35.0   8.0500
..      ...     ...   ...      ...
886       2    male  27.0  13.0000
887       1  female  19.0  30.0000
888       3  female   NaN  23.4500
889       1    male  26.0  30.0000
890       3    male  32.0   7.7500

[891 rows x 4 columns]

In [46]:
df2=df.replace(to_replace=['male','female'],value=[0,1])
df2.head()

Pclass  Sex   Age     Fare
0       3    0  22.0   7.2500
1       1    1  38.0  71.2833
2       3    1  26.0   7.9250
3       1    1  35.0  53.1000
4       3    0  35.0   8.0500

In [49]:
df2.isna().any()

Pclass    False
Sex       False
Age        True
Fare      False
dtype: bool

In [54]:
df2.Age.fillna(df2.Age.mean(),inplace=True)

In [55]:
df2.isna().any()

Pclass    False
Sex       False
Age       False
Fare      False
dtype: bool

In [57]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(df2,target,test_size=0.3)

In [62]:
print(x_train.shape)
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)

(623, 4)
(623,)
(268, 4)
(268,)


In [64]:
from sklearn.naive_bayes import GaussianNB
model=GaussianNB()

In [66]:
model.fit(x_train,y_train)

GaussianNB()

In [67]:
model.score(x_test,y_test)

0.753731343283582

In [68]:
x_test[:10]

Pclass  Sex        Age      Fare
699       3    0  42.000000    7.6500
39        3    1  14.000000   11.2417
319       1    1  40.000000  134.5000
510       3    0  29.000000    7.7500
175       3    0  18.000000    7.8542
553       3    0  22.000000    7.2250
63        3    0   4.000000   27.9000
77        3    0  29.699118    8.0500
569       3    0  32.000000    7.8542
191       2    0  19.000000   13.0000

In [69]:
y_test[:10]

699    0
39     1
319    1
510    1
175    0
553    1
63     0
77     0
569    1
191    0
Name: Survived, dtype: int64

In [70]:
model.predict(x_test[:10])

array([0, 1, 1, 0, 0, 0, 0, 0, 0, 0], dtype=int64)

In [73]:
model.predict_proba(x_test[:10])

array([[9.65385092e-01, 3.46149083e-02],
       [2.55242302e-01, 7.44757698e-01],
       [5.72367010e-04, 9.99427633e-01],
       [9.63194766e-01, 3.68052341e-02],
       [9.55348665e-01, 4.46513353e-02],
       [9.58946554e-01, 4.10534459e-02],
       [9.25444390e-01, 7.45556103e-02],
       [9.63503470e-01, 3.64965301e-02],
       [9.64301520e-01, 3.56984802e-02],
       [9.11106330e-01, 8.88936704e-02]])

In [74]:
from sklearn.model_selection import cross_val_score
cross_val_score(GaussianNB(),x_train,y_train,cv=5)

array([0.8       , 0.728     , 0.792     , 0.76612903, 0.86290323])

In [75]:
from sklearn.model_selection import cross_val_score
cross_val_score(GaussianNB(),x_test,y_test,cv=5)

array([0.75925926, 0.77777778, 0.75925926, 0.67924528, 0.75471698])